* Bagel (Slack)
  A service for getting people in a slack team to socialize with each other!

  Bagel is a piece of software that will pair up people in a specific channel whenever it is run. It will create a message between two people and encourage them to find time this week to have a conversation over lunch, over a coffee, or whatever. For people who have never talked to each other, this is a way to keep community ties strong! For people who already know each other, this is a good opportunity to catch up :)
* Motivation
  This program exists partially as a favour to a friend, but also as an opportunity to hone my Clojure development skills.
* Build Status
  TODO
* Code Style
  This project strives to follow the following style guide: https://guide.clojure.style/

  This project uses the following linting tools:
  * [[https://github.com/jonase/kibit][Kibit]]
  * [[https://github.com/jonase/eastwood][Eastwood]]
  * [[https://github.com/technomancy/slamhound][Slamhound]] (eventually)
* Technologies used:
** Built with:
   * [[https://www.clojure.org][Clojure]]
* Installation
  1. [[https://www.clojure.org/guides/getting_started][Install Clojure]]
  2. Check out this repo
  3. Determine and set the [[*How to configure][desired configuration]]
* Tests
** How to unit test:
   Because this is 99% integration code, unfortunately TODO
** How to lint:
   ~clojure -A:lint~
** How to run static analysis / idiomatic code conformance tools:
   ~clojure -A:kibit~
   ~clojure -A:eastwood~
* How to configure
  Bagel requires the following environment variables to be set up:

  * =BAGEL_SLACK_TOKEN=: The =xoxp=-prefixed token given to you when you installed Bagel into your workspace.
  * =BAGEL_CHANNEL_NAME=: The Slack channel containing the members you would like to pair off.
* How to Run
  ~clj -A:run~ (after configuring)
* Credits
  Thanks to [[https://github.com/maxmora][Christopher Spahr]] for motivating this project
* License
  (c) 2019 Gaelan D'costa

  This project is licensed under the [[https://www.eclipse.org/legal/epl-v10.html][Eclipse Public License Version 1.0]], as is Clojure itself.

